# Generated by Django 4.0.3 on 2022-04-21 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('categories', models.CharField(default='Business', max_length=50)),
                ('overview', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(choices=[('Precious Obinna', 'Precious Obinna'), ('Ohanyere Precious', 'Ohanyere Precious'), ('Jude Ohanyere', 'Jude Ohanyere')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('categories', models.CharField(default='Culture', max_length=50)),
                ('overview', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(choices=[('Precious Obinna', 'Precious Obinna'), ('Ohanyere Precious', 'Ohanyere Precious'), ('Jude Ohanyere', 'Jude Ohanyere')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Headline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('categories', models.CharField(choices=[('Sport', 'Sport'), ('Business', 'Business'), ('Marketing', 'Marketing'), ('Tech', 'Tech'), ('Food', 'Food'), ('Culture', 'Culture'), ('Design', 'Design'), ('Travel', 'Travel')], max_length=50)),
                ('overview', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(choices=[('Precious Obinna', 'Precious Obinna'), ('Ohanyere Precious', 'Ohanyere Precious'), ('Jude Ohanyere', 'Jude Ohanyere')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='LifeStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('categories', models.CharField(default='Lifestyle', max_length=50)),
                ('overview', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(choices=[('Precious Obinna', 'Precious Obinna'), ('Ohanyere Precious', 'Ohanyere Precious'), ('Jude Ohanyere', 'Jude Ohanyere')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(blank=True, choices=[('Sport', 'Sport'), ('Business', 'Business'), ('Marketing', 'Marketing'), ('Tech', 'Tech'), ('Food', 'Food'), ('Culture', 'Culture'), ('Design', 'Design'), ('Travel', 'Travel')], max_length=20)),
                ('title', models.CharField(max_length=1000)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('authors', models.CharField(blank=True, choices=[('Precious Obinna', 'Precious Obinna'), ('Ohanyere Precious', 'Ohanyere Precious'), ('Jude Ohanyere', 'Jude Ohanyere')], max_length=30)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Post1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(blank=True, choices=[('Sport', 'Sport'), ('Business', 'Business'), ('Marketing', 'Marketing'), ('Tech', 'Tech'), ('Food', 'Food'), ('Culture', 'Culture'), ('Design', 'Design'), ('Travel', 'Travel')], max_length=20)),
                ('title', models.CharField(max_length=1000)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('authors', models.CharField(blank=True, choices=[('Precious Obinna', 'Precious Obinna'), ('Ohanyere Precious', 'Ohanyere Precious'), ('Jude Ohanyere', 'Jude Ohanyere')], max_length=30)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Trending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('body', models.TextField(blank=True, null=True)),
                ('categories', models.CharField(choices=[('Sport', 'Sport'), ('Business', 'Business'), ('Marketing', 'Marketing'), ('Tech', 'Tech'), ('Food', 'Food'), ('Culture', 'Culture'), ('Design', 'Design'), ('Travel', 'Travel')], max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('authors', models.CharField(choices=[('Precious Obinna', 'Precious Obinna'), ('Ohanyere Precious', 'Ohanyere Precious'), ('Jude Ohanyere', 'Jude Ohanyere')], max_length=50)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
