# Generated by Django 4.0.3 on 2022-04-21 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('comment', models.TextField(blank=True)),
                ('authors', models.CharField(blank=True, choices=[('Precious Obinna', 'Precious Obinna'), ('Ohanyere Precious', 'Ohanyere Precious'), ('Jude Ohanyere', 'Jude Ohanyere')], max_length=30, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=1000)),
                ('message', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='CultureComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('comment', models.TextField(blank=True)),
                ('authors', models.CharField(blank=True, choices=[('Precious Obinna', 'Precious Obinna'), ('Ohanyere Precious', 'Ohanyere Precious'), ('Jude Ohanyere', 'Jude Ohanyere')], max_length=30, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='HeadlineComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('comment', models.TextField(blank=True)),
                ('authors', models.CharField(blank=True, choices=[('Precious Obinna', 'Precious Obinna'), ('Ohanyere Precious', 'Ohanyere Precious'), ('Jude Ohanyere', 'Jude Ohanyere')], max_length=30, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='LifestyleComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('comment', models.TextField(blank=True)),
                ('authors', models.CharField(blank=True, choices=[('Precious Obinna', 'Precious Obinna'), ('Ohanyere Precious', 'Ohanyere Precious'), ('Jude Ohanyere', 'Jude Ohanyere')], max_length=30, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='PostComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('comment', models.TextField(blank=True)),
                ('authors', models.CharField(blank=True, choices=[('Precious Obinna', 'Precious Obinna'), ('Ohanyere Precious', 'Ohanyere Precious'), ('Jude Ohanyere', 'Jude Ohanyere')], max_length=30, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='TrendComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('comment', models.TextField(blank=True)),
                ('authors', models.CharField(blank=True, choices=[('Precious Obinna', 'Precious Obinna'), ('Ohanyere Precious', 'Ohanyere Precious'), ('Jude Ohanyere', 'Jude Ohanyere')], max_length=30, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
